// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna o perfil do usu\xE1rio autenticado (id, nome, e-mail, fun\xE7\xE3o).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("profiles").select("id, nome, email, funcao, status").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? { id: ctx.getUserId() }) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-emissores.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.1";
import { z } from "npm:zod@^4.4.3";
var list_emissores_default = defineTool2({
  name: "list_emissores",
  title: "Listar emissores",
  description: "Lista emissores (empresas) da plataforma Buti\xE1 com filtros opcionais por nome, setor e rating. M\xE1ximo 100 resultados.",
  inputSchema: {
    search: z.string().trim().optional().describe("Busca em nome ou CNPJ."),
    setor: z.string().trim().optional().describe("Filtra por setor."),
    limit: z.number().int().min(1).max(100).optional().describe("M\xE1x. de resultados (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, setor, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    let query = supabase.from("empresas").select("id, nome, cnpj, setor, grupo_economico, rating, status, tipo").order("nome", { ascending: true }).limit(limit ?? 25);
    if (search) query = query.or(`nome.ilike.%${search}%,cnpj.ilike.%${search}%`);
    if (setor) query = query.eq("setor", setor);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { emissores: data, count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-emissor.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_emissor_default = defineTool3({
  name: "get_emissor",
  title: "Detalhes do emissor",
  description: "Retorna detalhes de um emissor por CNPJ, incluindo emiss\xF5es vinculadas e \xFAltimas an\xE1lises.",
  inputSchema: {
    cnpj: z2.string().trim().min(11).describe("CNPJ do emissor (com ou sem formata\xE7\xE3o).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ cnpj }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data: empresa, error } = await supabase.from("empresas").select("*").eq("cnpj", cnpj).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!empresa) {
      return { content: [{ type: "text", text: `Nenhum emissor com CNPJ ${cnpj}.` }], isError: true };
    }
    const [{ data: emissoes }, { data: analises }] = await Promise.all([
      supabase.from("emissoes").select("*").eq("empresa_id", empresa.id).limit(50),
      supabase.from("analises").select("id, isin, recomendacao, decisao, data_inicio, data_conclusao, analista_responsavel").eq("empresa_id", empresa.id).order("data_inicio", { ascending: false }).limit(20)
    ]);
    const payload = { empresa, emissoes: emissoes ?? [], analises: analises ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-analises.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.100.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_analises_default = defineTool4({
  name: "list_analises",
  title: "Listar an\xE1lises",
  description: "Lista an\xE1lises de cr\xE9dito/a\xE7\xF5es com filtros opcionais. Ordenadas pelas mais recentes.",
  inputSchema: {
    empresa_id: z3.string().uuid().optional().describe("Filtra por emissor (id)."),
    recomendacao: z3.string().trim().optional().describe("Ex.: Compra, Venda, Neutro."),
    analista: z3.string().trim().optional().describe("Nome/id do analista respons\xE1vel."),
    limit: z3.number().int().min(1).max(100).optional().describe("M\xE1x. de resultados (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ empresa_id, recomendacao, analista, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    let query = supabase.from("analises").select(
      "id, empresa_id, isin, recomendacao, decisao, conviccao, data_inicio, data_conclusao, analista_responsavel, prazo, preco_medio"
    ).order("data_inicio", { ascending: false }).limit(limit ?? 25);
    if (empresa_id) query = query.eq("empresa_id", empresa_id);
    if (recomendacao) query = query.ilike("recomendacao", recomendacao);
    if (analista) query = query.ilike("analista_responsavel", `%${analista}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { analises: data, count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-posicoes.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.100.1";
import { z as z4 } from "npm:zod@^4.4.3";
var list_posicoes_default = defineTool5({
  name: "list_posicoes",
  title: "Listar posi\xE7\xF5es",
  description: "Lista posi\xE7\xF5es da carteira em uma data (padr\xE3o: mais recente). Filtros opcionais por ISIN e classe do produto.",
  inputSchema: {
    val_date: z4.string().trim().optional().describe("Data de refer\xEAncia YYYY-MM-DD. Padr\xE3o: \xFAltima."),
    isin: z4.string().trim().optional().describe("Filtra por ISIN."),
    product_class: z4.string().trim().optional().describe("Classe do produto (ex.: DEB, LFT)."),
    limit: z4.number().int().min(1).max(200).optional().describe("M\xE1x. de resultados (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ val_date, isin, product_class, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = createClient5(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    let dateFilter = val_date;
    if (!dateFilter) {
      const { data: latest } = await supabase.from("posicoes").select("val_date").order("val_date", { ascending: false }).limit(1).maybeSingle();
      dateFilter = latest?.val_date;
    }
    if (!dateFilter) {
      return { content: [{ type: "text", text: "Nenhuma posi\xE7\xE3o encontrada." }] };
    }
    let query = supabase.from("posicoes").select(
      "id, val_date, isin, product, product_class, amount, financial_price, duration_du, yield, implied_spread"
    ).eq("val_date", dateFilter).order("amount", { ascending: false }).limit(limit ?? 50);
    if (isin) query = query.eq("isin", isin);
    if (product_class) query = query.eq("product_class", product_class);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ val_date: dateFilter, posicoes: data }) }],
      structuredContent: { val_date: dateFilter, posicoes: data, count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "oxgbtbdkvxyraxbtpdjt";
var mcp_default = defineMcp({
  name: "butia-research-mcp",
  title: "Buti\xE1 Research Platform",
  version: "0.1.0",
  instructions: "Ferramentas de leitura para a Buti\xE1 Research Platform: perfil do usu\xE1rio, emissores, an\xE1lises de cr\xE9dito e posi\xE7\xF5es da carteira. Todas as chamadas respeitam a autentica\xE7\xE3o e RLS do usu\xE1rio conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_emissores_default, get_emissor_default, list_analises_default, list_posicoes_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
